### ISSUE TITLE
Maybe we should consider using package for a better publish experiences?

### ISSUE THREAD

**Issue by Albert-Gao** [Albert-Gao/modern-es6-npm-boilerplate#3]
Something like [np](https://github.com/sindresorhus/np) ?
Very interactive, but seems it is too strict, so we need to make sure our example work with that.

Or any other suggestion is welcome.

**Comment by vaibhavmule** [comment]
Looks like a good idea.

**Comment by Albert-Gao** [comment]
Thanks for the backing, @vaibhavmule 
I tried `np` in my own package, has some problems with promise handling, already got some issues on its list, don't know when will be fixed, will watch for it or try to find a new one.

**Comment by vaibhavmule** [comment]
what exactly issue you are facing?
You tried with this project or another package of yours.

**Comment by Albert-Gao** [comment]
I tried that `np` when I tried to publish my own package: [veasy](https://github.com/Albert-Gao/veasy)

2 Problems:

1. after changing that version number from `old` to `new`, it will still show the successful message as `old ver published`

1. will `tag` but won't `publish` since always ends with error because of the promise issue which like in this [issue](https://github.com/sindresorhus/np/issues/190), I use jest though

I published a new issue there with all the npm error log, hope it helps:
https://github.com/sindresorhus/np/issues/192

**Comment by vaibhavmule** [comment]
It's good that you have raised the issue, I have tried simulating the bug and trying to fix, no luck as of now.

**Comment by Albert-Gao** [comment]
really thanks!

it would be good if you can reproduce that issue. I don't even know if it's a universal problem or not. or just because not compatible with some of the packages we are using. for instance, the first log is for rimraf.

**Comment by vaibhavmule** [comment]
Can you please check it as np has released 2.16.1

source: https://github.com/sindresorhus/np/pull/195

**Comment by Albert-Gao** [comment]
Thanks for the info, will try, but seems not that positive according to [this](https://github.com/sindresorhus/np/issues/192)

**Comment by Albert-Gao** [comment]
Works for me now!

**Comment by Albert-Gao** [comment]
Very nice experiences, try the new `npm run pub`, `np` works pretty well now

**Comment by vaibhavmule** [comment]
Okay cool.
