### ISSUE TITLE
What is benefits of rimraf package ?

### ISSUE THREAD

**Issue by vaibhavmule** [Albert-Gao/modern-es6-npm-boilerplate#6]

**Comment by Albert-Gao** [comment]
For handling the different implementation of `removing folder` from systems. But if it's the cause of the problems, we could look for an alternative. :) What do you think?

**Comment by vaibhavmule** [comment]
Oh, I see. 

It handles the error if you are trying to remove file or directory. Nodejs native API throws an error if you trying to `fs.rmdir('/path')` on file.
